import React, { useState } from "react";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Copy,
  Check,
  ExternalLink,
  Sparkles,
  Bookmark,
} from "lucide-react";
import { downloadMarkdownFile } from "../../../lib/utils/download-markdown";

interface OutputScreenProps {
  title: string;
  actionBadge: string;
  markdownContent: string;
  sourceUrl: string;
  onBack: () => void;
}

export function OutputScreen({
  title,
  actionBadge,
  markdownContent,
  sourceUrl,
  onBack,
}: OutputScreenProps) {
  const [copied, setCopied] = useState(false);
  const [bookmarked, setBookmarked] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleBookmark = () => {
    setBookmarked(!bookmarked);
  };

  return (
    <motion.div
      initial={{ x: 420, opacity: 0 }}
      animate={{ x: 0, opacity: 1 }}
      exit={{ x: 420, opacity: 0 }}
      transition={{ type: "spring", stiffness: 300, damping: 30 }}
      className="fixed inset-0 bg-[#09090b] z-50 flex flex-col justify-between w-[420px] min-h-screen"
    >
      {/* Top Navigation */}
      <div className="h-16 border-b border-white/10 px-5 flex items-center justify-between bg-[#09090b]/90 backdrop-blur-xl shrink-0">
        <button
          onClick={onBack}
          className="flex items-center gap-1.5 text-xs text-[#71717a] hover:text-white transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Suggestions</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleBookmark}
            className={`p-1.5 rounded-lg border transition-all ${
              bookmarked
                ? "bg-[#4F8DFF]/20 border-[#4F8DFF] text-[#4F8DFF]"
                : "bg-white/5 border-white/10 text-[#71717a] hover:text-white"
            }`}
            title="Save to Dashboard"
          >
            <Bookmark className="w-3.5 h-3.5 fill-current" />
          </button>

          <span className="text-[10px] uppercase tracking-wider px-2.5 py-1 rounded-full bg-[#8B5CF6]/20 border border-[#8B5CF6]/40 text-[#8B5CF6] font-semibold">
            {actionBadge}
          </span>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 p-5 overflow-y-auto space-y-4">
        <div>
          <h2 className="text-lg font-bold text-white tracking-tight leading-snug">
            {title}
          </h2>
          <a
            href={sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-[#4F8DFF] hover:underline flex items-center gap-1 mt-1 truncate"
          >
            <span>{sourceUrl}</span>
            <ExternalLink className="w-3 h-3 shrink-0" />
          </a>
        </div>

        {/* Markdown Render Container */}
        <div className="p-4 rounded-2xl bg-white/[0.04] border border-white/10 text-sm text-[#f4f4f5] leading-relaxed whitespace-pre-wrap font-sans">
          {markdownContent}
        </div>
      </div>

      {/* Bottom Footer Actions */}
      <div className="p-4 border-t border-white/10 bg-[#09090b]/90 backdrop-blur-xl flex items-center justify-between shrink-0">
        <span className="text-[11px] text-[#71717a] flex items-center gap-1">
          <Sparkles className="w-3 h-3 text-[#10B981]" />
          Generated by Google Gemini 2.5 Flash
        </span>

        <div className="flex items-center gap-2">
          <button
            onClick={() => downloadMarkdownFile(title, markdownContent)}
            className="px-3 py-2 rounded-xl text-xs font-semibold bg-white/5 border border-white/10 text-white hover:bg-white/10 transition-all"
          >
            Download .MD
          </button>
          <button
            onClick={handleCopy}
            className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all shadow-glass ${
              copied
                ? "bg-[#10B981] text-white"
                : "bg-gradient-to-r from-[#4F8DFF] to-[#8B5CF6] text-white hover:opacity-95"
            }`}
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Markdown</span>
              </>
            )}
          </button>
        </div>
      </div>
    </motion.div>
  );
}
